export { default as Face } from './Face'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Search } from './Search'
export { default as Settings } from './Settings'
export { default as ShoppingCart } from './ShoppingCart'
